# Generated by Django 5.2.6 on 2025-09-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('match_worn_vintage', 'Match Worn Vintage'), ('player_issue_vintage', 'Player Issue Vintage'), ('replica_vintage', 'Replica Vintage'), ('reissue_retro', 'Reissue Retro'), ('special_edition_vintage', 'Special Edition Vintage'), ('analysis', 'Analysis')], default='match_worn_vintage', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('season', models.CharField(max_length=9)),
                ('exlusive', models.BooleanField(default=False)),
                ('history_value', models.CharField(choices=[('classic', 'Classic'), ('signed_vintage', 'Signed Vintage'), ('limited_edition', 'Limited Edition'), ('historical_matches', 'Historical Matches')], default='classic', max_length=50)),
            ],
        ),
    ]
