# Generated by Django 5.2.6 on 2025-09-11 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='history_value',
            field=models.CharField(choices=[('classic', 'Classic'), ('signed_vintage', 'Signed Vintage'), ('limited_edition', 'Limited Edition'), ('historical_matches', 'Historical Matches')], default='classic', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('match_worn_vintage', 'Match Worn Vintage'), ('player_issue_vintage', 'Player Issue Vintage'), ('replica_vintage', 'Replica Vintage'), ('reissue_retro', 'Reissue Retro'), ('special_edition_vintage', 'Special Edition Vintage'), ('analysis', 'Analysis')], default='match_worn_vintage', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
